name: news_app
description: News App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  flutter_modular: ^5.0.2
  animations: ^2.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shimmer: ^2.0.0
  unicons: ^2.1.0
  sqflite: ^2.0.2+1
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true